# nginx/nginx.conf
# Nginx principal — reverse proxy + load balancer
# ============================================================ #

# ── Load Balancer ───────────────────────────────── 
#  = Define el grupo de backends = #
#  = Nginx distribuye requests entre ellos (round-robin por defecto) = #
upstream backend_pool {
  server backend:5000;
  server backend_2:5000;
}


# ── Server ─────────────────────────────────
server {
  listen 80;
  server_name localhost;

  location / {
    proxy_pass http://frontend:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/ {
    proxy_pass http://backend_pool:5000/;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout 10s;
    proxy_read_timeout 60s;

    proxy_next_upstream error timeout http_500;
  }

  location /docs {
    proxy_pass http://backend:5000/docs;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /openapi.json {
    proxy_pass http://backend:5000/openapi.json;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

}
