# nginx/nginx.conf
# Nginx principal — reverse proxy + load balancer
# ============================================================ #

# ── Load Balancer ───────────────────────────────── 
#  = Define el grupo de backends = #
#  = Nginx distribuye requests entre ellos (round-robin por defecto) = #
upstream backend_pool {
  # Round-robin: cada request va al siguiente servidor
  # backend_1 y backend_2 son nombres de servicio en Docker Compose
  server backend_1:5000; 
  server backend_2:5001; 

  # Opciones útiles:
  # least_conn;   → envía al servidor con menos conexiones activas
  # ip_hash;      → mismo cliente siempre al mismo backend (sticky session)
}


# ── Server ─────────────────────────────────
server {
  listen: 80; 
  server_name localhost; 

  # === Frontend === #
  # - Todo lo que no sea /api/ va al frontend React - #}
  location / {
    proxy_pass http://frontend:80; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr
  }

  # ==== API - Load Balancer - ==== # 
  # - Requests a /api/ se distribuyen entre los backends - #
  location /api/ {
    proxy_pass http://backend_pool:

    # Headers importantes para que FastAPI sepa el origen real #
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;


    # Timeout #
    proxy_connect_timeout  10s;
    proxy_read_timeout     60s;

    # - Si un backend falla, reintenta en el siguiente - # 
    proxy_next_upstream error timeout http_500; 
  
  }

}


# ── Swagger UI | Only Backend_1 ─────────────────────────────────
# =  /docs no tiene sentido balancear — va directo al primero = #
  location /docs {
    proxy_pass http://backend_15000/docs
    proxy_set_header Host $host; 
  }

  location /openapi.json {
    proxy_pass http://backend_1:5000/openapi.json; 
    proxy_set_header Host $host; 
  }